# =============================================================================
# EXTERNAL SECRETS FOR GRAFANA (from Vault)
# =============================================================================

{{- range $secret := .Values.grafanaEso.secrets }}
{{- if not (eq $secret.is_need_eso false) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.external_secret_name }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: {{ $secret.refresh_interval | default $.Values.esoResourcesConfig.externalSecretRefreshInterval }}
  refreshPolicy: {{ $.Values.esoResourcesConfig.externalSecretRefreshPolicy }}
  secretStoreRef:
    kind: SecretStore
    name: {{ $.Values.grafanaEso.secretStoreName }}
  target:
    name: {{ $secret.target_secret_name }}
  dataFrom:
    - extract:
        key: {{ $.Values.grafanaEso.kvEnginePath }}/data{{ $secret.vault_path }}
{{- end }}
{{- end }}
