apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.grafanaEso.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.esoResourcesConfig.secretStoreRefreshInterval }}
  provider:
    vault:
      server: {{ .Values.grafanaEso.vaultServerUrl }}
      path: {{ .Values.grafanaEso.kvEnginePath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.grafanaEso.roleName }}
          serviceAccountRef:
            name: {{ .Values.grafanaEso.saName }}
