# =============================================================================
# SERVICE ACCOUNT FOR VAULT AUTHENTICATION (GitLab Runner)
# =============================================================================

{{- if not (eq .Values.runnerEso.isNeedEso false) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runnerEso.saName }}
  namespace: {{ .Values.namespace }}
{{- end }}
