namespace: ""

ingressClass: ""
clusterIssuer: ""
vpnOnlyEnabled: false
vpnIngressMiddlewares: ""

traefik:
  namespace: ""
  entryPoints:
    web: ""
    websecure: ""

grafana:
  ingress:
    domain: ""
    secretName: ""
    httpEnable: false
    httpsEnable: false
  port: 3000
