---
# Default deny all traffic in vector namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
# Allow DNS for all pods in vector namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---
# Allow all traffic between pods inside vector namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-traffic
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}

---
# Vector: egress to Loki (logs) + egress to kube-apiserver (kubernetes_logs source)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vector
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.vector.serviceLabel }}
  policyTypes:
    - Egress
  egress:
    # Loki
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.loki.namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.loki.serviceLabel }}
      ports:
        - protocol: TCP
          port: {{ .Values.loki.port }}
    # External (TCP/443) — для kubernetes_logs source (доступ к kube-apiserver)
    - ports:
        - protocol: TCP
          port: 443

# =============================================================================
# LOKI — ingress from vector namespace
# =============================================================================

---
# Allow Vector ingress to Loki
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.namespace }}-allow-loki"
  namespace: {{ .Values.loki.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.loki.serviceLabel }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.vector.serviceLabel }}
      ports:
        - protocol: TCP
          port: {{ .Values.loki.port }}
