# =============================================================================
# Playbook: Collect node information (network interfaces, OS, etc.)
# Usage: ansible-playbook -i hosts.yaml node-info.yaml
# =============================================================================
---
- name: Collect node information
  hosts: managers:workers
  gather_facts: true

  tasks:
    - name: Display node summary
      debug:
        msg:
          - "Node: {{ inventory_hostname }}"
          - "SSH Host: {{ ansible_host }}"
          - "OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
          - "Kernel: {{ ansible_facts['kernel'] }}"
          - "Architecture: {{ ansible_facts['architecture'] }}"
          - "CPU Cores: {{ ansible_facts['processor_vcpus'] }}"
          - "RAM: {{ (ansible_facts['memtotal_mb'] / 1024) | round(1) }} GB"

    - name: Get network interfaces (ip addr show)
      command: ip addr show
      register: ip_addr_output
      changed_when: false

    - name: Display network interfaces
      debug:
        msg: "{{ ip_addr_output.stdout_lines }}"
