namespace: ""

ingress:
  uiDomain: ""
  rpcDomain: ""
  ingressClass: ""
  entrypoint: ""
  clusterIssuer: ""
  uiSecretName: ""
  rpcSecretName: ""
  vpnOnlyEnabled: true
  httpEnabled: false

traefik:
  namespace: ""
