{{- if not (eq .Values.zitadelEso.isNeedEso false) }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.zitadelEso.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.esoResourcesConfig.secretStoreRefreshInterval }}
  provider:
    vault:
      server: {{ .Values.zitadelEso.vaultServerUrl }}
      path: {{ .Values.zitadelEso.kvEnginePath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.zitadelEso.roleName }}
          serviceAccountRef:
            name: {{ .Values.zitadelEso.saName }}
{{- end }}
