{{- range .Values.gitOps }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: "{{ $.Values.namespace }}"
spec:
  sourceRepos:
    {{- toYaml .project.sourceRepos | nindent 4 }}
  sourceNamespaces:
    {{- toYaml (.project.sourceNamespaces | default (list "*")) | nindent 4 }}
  destinations:
    {{- toYaml .project.destinations | nindent 4 }}
  clusterResourceBlacklist:
    {{- toYaml (.project.clusterResourceBlacklist | default (list (dict "group" "*" "kind" "*"))) | nindent 4 }}
  namespaceResourceBlacklist:
    {{- toYaml (.project.namespaceResourceBlacklist | default (list (dict "group" "argoproj.io" "kind" "AppProject") (dict "group" "argoproj.io" "kind" "Application"))) | nindent 4 }}
{{- $projectName := .name }}
{{- $namespace := $.Values.namespace }}
{{- range .apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: "{{ $namespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: {{ $projectName }}
  revisionHistoryLimit: {{ .revisionHistoryLimit | default 3 }}
  source:
    repoURL: "{{ .repoURL }}"
    targetRevision: "{{ .targetRevision }}"
    path: "{{ .path }}"
  destination:
    server: "{{ .destinationServer }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=background
    retry:
      limit: {{ .retry.limit }}
      backoff:
        duration: {{ .retry.backoff.duration }}
        factor: {{ .retry.backoff.factor }}
        maxDuration: {{ .retry.backoff.maxDuration }}
{{- end }}
{{- end }}
