namespace: ""

hubbleUi:
  domain: ""
  clusterIssuer: ""
  ingressClass: ""
  secretName: ""
  vpnOnlyEnabled: true
  httpEnable: false
  httpsEnable: false

traefik:
  namespace: ""
  entryPoints:
    web: ""
    websecure: ""

# Node IPs for cluster internal traffic rules
nodeIps: []