# =============================================================================
# Verify Helm releases in a namespace
# =============================================================================
# Params:
#   - dto_helm_namespace: Namespace to list Helm releases
#   - label_name: Label prefix for task names (optional, default: 'verify-helm')
# =============================================================================

- name: "[{{ label_name }}] Assert all dto params are provided"
  assert:
    that:
      - label_name is defined
      - label_name | length > 0
      - dto_helm_namespace is defined
      - dto_helm_namespace | length > 0
    fail_msg: "tasks-verify-helm: all params required: label_name, dto_helm_namespace"
  delegate_to: "{{ master_manager_fact }}"
  run_once: true
  tags: [always]

- name: "[{{ label_name }}] Verify Helm releases"
  command: helm list -n {{ dto_helm_namespace }}
  register: helm_list
  changed_when: false
  delegate_to: "{{ master_manager_fact }}"
  run_once: true
  tags: [always]

- name: "[{{ label_name }}] Print Helm releases"
  debug:
    msg: "{{ helm_list.stdout_lines }}"
  delegate_to: "{{ master_manager_fact }}"
  run_once: true
  tags: [always]