# =============================================================================
# Wait for secret in k8s
# =============================================================================
# DESCRIPTION - here
# DESCRIPTION - here
# DESCRIPTION - here
# DESCRIPTION - here
# params
#  - label_name
#  - dto_wait_secret_name
#  - dto_wait_secret_namespace
# Wait retries/delay are hardcoded: retries=30, delay=5s.
# =============================================================================

- name: "[{{ label_name }}] Wait for k8s Secret to appear"
  command: kubectl get secret {{ dto_wait_secret_name }} -n {{ dto_wait_secret_namespace }}
  register: _secret_wait_res
  until: _secret_wait_res.rc == 0
  retries: 30
  delay: 5
  changed_when: false
  delegate_to: "{{ master_manager_fact }}"
  run_once: true
  tags: [always]
