all:
  vars:
    # ------
    # Traefik
    # ------
    traefik_chart_version: "38.0.2"
    traefik_version: "v3.6.2"
    traefik_namespace: "traefik-lb"
    traefik_daemonset_name: "traefik-lb"
    traefik_ingress_class: "traefik-lb"
    traefik_web_entrypoint: "web" # WARNING: DO NOT CHANGE - hardcoded in helm chart
    traefik_websecure_entrypoint: "websecure" # WARNING: DO NOT CHANGE - hardcoded in helm chart
    traefik_dashboard_domain: "traefik-dashboard-k8s-v2.drawapp.ru"
    traefik_dashboard_vpn_only_enabled: false
    traefik_dashboard_https_secret_name: "cert-traefik-dashboard"
    traefik_dashboard_service_name: "traefik-dashboard"
    traefik_dashboard_ingress_http_enable: false
    traefik_dashboard_ingress_https_enable: true
    traefik_dashboard_cluster_issuer_name: "acme-prod"
    traefik_dashboard_ingress_class_name: "traefik-lb"
    # Tolerations (DaemonSet)
    traefik_tolerations:
      - operator: "Exists"
    traefik_node_selector: {}
    traefik_resources: {}
    # Traefik ports
    traefik_traefik_port: 8080 # NOT CHANGE
    traefik_web_port: 80 # NOT CHANGE
    traefik_websecure_port: 443 # NOT CHANGE
    traefik_prometheus_port: 9200
    # ServiceMonitor (prometheus-operator)
    traefik_service_monitor_enabled: true
    traefik_service_monitor_interval: "30s"
    traefik_service_monitor_scrape_timeout: "15s"
    # Дополнительные labels для совпадения с serviceMonitorSelector
    traefik_service_monitor_additional_labels: {}
    # Middlewares
    traefik_middlewares:
      - name: http-to-https
        spec:
          redirectRegex:
            regex: "^http://(.+)"
            replacement: "https://${1}"
            permanent: true
      - name: http-www-to-https
        spec:
          redirectRegex:
            regex: "^http://www.(.+)"
            replacement: "https://${1}"
            permanent: true
      - name: http-www-to-http
        spec:
          redirectRegex:
            regex: "^http://www.(.+)"
            replacement: "http://${1}"
            permanent: true
      - name: https-www-to-https
        spec:
          redirectRegex:
            regex: "^https://www.(.+)"
            replacement: "https://${1}"
            permanent: true
      - name: all-to-https
        spec:
          redirectRegex:
            regex: "(^https://www.|^http://www.|^http://)(.+)"
            replacement: "https://${2}"
            permanent: true
    # Helm timeouts
    traefik_helm_timeout: "5m"
    traefik_rollout_timeout: "300s"
