# =============================================================================
# ARGOCD RPC INGRESS - HTTPS
# =============================================================================

{{- if .Values.ingress.httpsEnable }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.rpcSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.rpcSecretName }}
  dnsNames:
    - "{{ .Values.ingress.rpcDomain }}"
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
---
# =============================================================================
# INGRESSROUTE FOR ARGOCD RPC (gRPC) — HTTPS (Traefik)
# =============================================================================
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-rpc-https
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.ingressClass }}"
spec:
  entryPoints:
    - {{ .Values.traefik.entryPoints.websecure }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.rpcDomain }}`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      {{- if .Values.ingress.vpnOnlyEnabled }}
      middlewares:
        {{- range .Values.vpnIngressRouteMiddlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace }}
        {{- end }}
      {{- end }}
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: {{ .Values.ingress.rpcSecretName }}
{{- end }}
