# =============================================================================
# INGRESSROUTE FOR ARGOCD UI (Traefik)
#   enabled    → рендерить IngressRoute
#   tlsEnabled → websecure entrypoint + tls-блок; иначе web, без tls
# =============================================================================
{{- if .Values.uiIngressConfig.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ui
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.uiIngressConfig.ingressClass }}"
spec:
  entryPoints:
    {{- if .Values.uiIngressConfig.tlsEnabled }}
    - {{ .Values.traefik.entryPoints.websecure }}
    {{- else }}
    - {{ .Values.traefik.entryPoints.web }}
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.uiIngressConfig.domain }}`)
      priority: 10
      {{- if .Values.uiIngressConfig.vpnOnlyEnabled }}
      middlewares:
        {{- range .Values.uiIngressConfig.vpnIngressRouteMiddlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace }}
        {{- end }}
      {{- end }}
      services:
        - name: argocd-server
          port: 80
  {{- if and .Values.uiIngressConfig.tlsEnabled .Values.uiIngressConfig.tlsSecretName }}
  tls:
    secretName: {{ .Values.uiIngressConfig.tlsSecretName }}
  {{- end }}
{{- end }}
