# =============================================================================
# INGRESSROUTE FOR ARGOCD RPC (gRPC) — HTTP (Traefik)
# =============================================================================

{{- if .Values.ingress.httpEnable }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-argocd-rpc-http
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.ingressClass }}"
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints.web }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.rpcDomain }}`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      {{- if .Values.ingress.vpnOnlyEnabled }}
      middlewares:
        - name: vpn-only
          namespace: {{ .Values.traefik.namespace }}
      {{- end }}
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
{{- end }}
