apiVersion: v1
kind: Pod
metadata:
  name: haproxy-apiserver-lb
  namespace: kube-system
  annotations:
    # Triggers pod restart when haproxy.cfg changes
    checksum/config: "{{ haproxy_config_content | hash('sha256') }}"
  labels:
    component: haproxy-apiserver-lb
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
    - name: haproxy
      image: {{ haproxy_apiserver_lb_image }}
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
      livenessProbe:
        httpGet:
          path: /healthz
          port: {{ haproxy_apiserver_lb_healthz_port }}
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /healthz
          port: {{ haproxy_apiserver_lb_healthz_port }}
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          readOnly: true
  volumes:
    - name: haproxy-config
      hostPath:
        path: /etc/kubernetes/haproxy-apiserver-lb.cfg
        type: File