---
namespace: ""

loki:
  image: ""
  port: 0
  s3:
    secretName: ""
    accessKeyIdKey: ""
    secretAccessKeyKey: ""

emptyDir:
  sizeLimit: ""

config_yaml: ""

tolerations: []
nodeSelector: {}
resources: {}

# Custom K8s objects to render (operator-side, default empty)
extraObjects: []
