# =============================================================================
# CLUSTER ISSUERS (raw spec, rendered as-is from inventory)
# =============================================================================

{{- range .Values.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
{{ toYaml .spec | indent 2 }}
{{- end }}
