# =============================================================================
# CLUSTER ISSUERS FOR LET'S ENCRYPT
# =============================================================================

{{- range .Values.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    server: {{ .server }}
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ .privateKeySecretName }}
    solvers:
      {{- range .solvers }}
      - http01:
          ingress:
            ingressClassName: {{ .ingressClass }}
            ingressTemplate:
              metadata:
                annotations:
                  {{- range $k, $v := .ingressAnnotations }}
                  {{ $k | quote }}: {{ $v | quote }}
                  {{- end }}
            podTemplate:
              metadata:
                labels:
                  {{- range $k, $v := .podLabels }}
                  {{ $k }}: {{ $v }}
                  {{- end }}
      {{- end }}
{{- end }}
