namespace: ""

grafana:
  port: 3000
  image:
    name: "grafana/grafana"
    tag: "12.4.2"
  installPlugins: "grafana-piechart-panel"

adminSecret:
  name: "eso-grafana-admin"
  usernameKey: "username"
  passwordKey: "password"

pvc:
  storageClassName: ""
  storageSize: ""
  accessMode: ""

tolerations: []
nodeSelector: {}
resources: {}
