namespace: ""

grafana:
  port: 3000
  image:
    name: "grafana/grafana"
    tag: "12.4.2"
  installPlugins: ""
  externalUrl: ""

adminSecret:
  name: ""
  usernameKey: ""
  passwordKey: ""

pvc:
  storageClassName: ""
  storageSize: ""
  accessMode: ""

tolerations: []
nodeSelector: {}
resources: {}
