apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/managed-by: Helm
spec:
  {{- .Values.vaultSpec | toYaml | nindent 2 }}
