apiVersion: v2
name: prometheus-operator-alertmanager
description: Alertmanager instance (CRD + AlertmanagerConfig + Service) managed by prometheus-operator
type: application
version: 0.1.0
appVersion: "0.28.1"
