namespace: ""

# DNS domain for internal service resolution
clusterDomain: ""

traefik:
  namespace: ""

# Vault namespace for SecretStore connection
vault:
  namespace: ""

# ESO settings
eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  kvEnginePath: ""
  secrets: []
