# Namespace
namespace: gitlab

# SSH port for HAProxy
sshPortExternal: 3714

# GitLab settings
gitlab:
  ingressClass: ""
  domain: ""
  registryDomain: ""
  pagesDomain: ""
  clusterIssuer: ""
  uiSecretName: ""
  registrySecretName: ""
  pagesSecretName: ""
  vpnOnlyEnabled: false
  httpEnable: false
  httpsEnable: false

# MinIO settings (Console + API ingress)
minio:
  ingressClass: ""
  consoleDomain: ""
  apiDomain: ""
  clusterIssuer: ""
  consoleSecretName: ""
  apiSecretName: ""
  vpnOnlyEnabled: false
  httpEnable: false
  httpsEnable: false

# Traefik namespace for middleware
traefik:
  namespace: ""
  entryPoints:
    web: ""
    websecure: ""

# HAProxy settings for SSH TCP ingress
haproxy:
  namespace: ""
  ingressClass: ""
