apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-system-grafana-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mon-system-grafana-postgresql
    app.kubernetes.io/instance: mon-system-grafana-postgresql-{{ .Values.namespace }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mon-system
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mon-system-grafana-postgresql
      app.kubernetes.io/instance: mon-system-grafana-postgresql-{{ .Values.namespace }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mon-system-grafana-postgresql
        app.kubernetes.io/instance: mon-system-grafana-postgresql-{{ .Values.namespace }}
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: mon-system
        app.kubernetes.io/managed-by: Helm
    spec:
      automountServiceAccountToken: false
      tolerations: {{ .Values.tolerations | toJson }}
      nodeSelector: {{ .Values.nodeSelector | toJson }}
      affinity: {{ .Values.affinity | toJson }}
      containers:
        - name: postgresql
          image: {{ .Values.image }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: {{ .Values.credentials.usernameKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: {{ .Values.credentials.passwordKey }}
            - name: POSTGRES_DB
              value: {{ .Values.databaseName | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgresql
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources: {{ .Values.resources | toJson }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mon-system-grafana-postgresql
