apiVersion: v1
kind: Service
metadata:
  name: mon-system-grafana-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mon-system-grafana-postgresql
    app.kubernetes.io/instance: mon-system-grafana-postgresql-{{ .Values.namespace }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mon-system
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: mon-system-grafana-postgresql
    app.kubernetes.io/instance: mon-system-grafana-postgresql-{{ .Values.namespace }}
