---
# PostgreSQL configuration
namespace: gitlab

# Database identity
databaseName: "gitlabhq_production"

image: "postgres:17.9-alpine3.23"

# Storage
storageClass: lh-major-multi-best-effort
storageSize: 20Gi

# Credentials secret (from ESO)
credentials:
  secretName: ""
  usernameKey: ""
  passwordKey: ""

# Custom K8s objects to render (operator-side, default empty)
extraObjects: []
