namespace: ""

loki:
  image:
    name: ""
    tag: ""
  port: 3100
  pvc_subpath: ""

storage:
  class: ""
  size: ""

config:
  schema_from_date: ""
  retention_period: ""
  max_line_size: ""
  ingestion_rate_mb: 0
  ingestion_burst_size_mb: 0

tolerations: []
nodeSelector: {}
resources: {}
