namespace: ""

loki:
  image:
    name: ""
    tag: ""
  port: 3100

pvc:
  accessMode: ""
  storageClassName: ""
  storageSize: ""
  subpath: ""

config_yaml: ""

tolerations: []
nodeSelector: {}
resources: {}
