# =============================================================================
# HUBBLE UI INGRESS - HTTP
# =============================================================================

{{- if .Values.hubbleUi.httpEnable }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-ui-http
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.hubbleUi.ingressClass }}"
    traefik.ingress.kubernetes.io/router.entrypoints: "{{ .Values.traefik.entryPoints.web }}"
    {{- if .Values.hubbleUi.vpnOnlyEnabled }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.vpnIngressMiddlewares }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.hubbleUi.ingressClass }}
  rules:
    - host: {{ .Values.hubbleUi.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hubble-ui
                port:
                  number: 80
{{- end }}
