# Namespace
namespace: ""

# IngressClass
ingressClass: ""

# Traefik entryPoints
traefik:
  entryPoints:
    web: ""
    websecure: ""

# Middlewares
middlewares: []

# VPN Middlewares (from vpn-rules.yaml)
vpnMiddlewares: []
vpnIngressMiddlewares: ""

# Dashboard Ingress
dashboard:
  serviceName: ""
  domain: ""
  secretName: ""
  clusterIssuer: ""
  # VPN-only middleware (restrict access to VPN IPs)
  vpnOnlyEnabled: true
  httpEnable: false
  httpsEnable: false
