# =============================================================================
# INGRESSROUTE FOR ZITADEL UI — HTTP (Traefik)
# =============================================================================

{{- if .Values.ingress.httpEnable }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel-ui-http
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.ingressClass }}"
spec:
  entryPoints:
    - {{ .Values.traefik.entryPoints.web }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.domain }}`)
      priority: 10
      {{- if .Values.ingress.vpnOnlyEnabled }}
      middlewares:
        {{- range .Values.ingress.vpnIngressRouteMiddlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace }}
        {{- end }}
      {{- end }}
      services:
        - name: zitadel
          port: 8080
          scheme: h2c
{{- end }}
