apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestash
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: filestash
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
