[oldhost]
type = s3
provider = Minio
access_key_id = xxx
secret_access_key = xxx
endpoint = http://localhost:39000
region = us-east-1
force_path_style = true

[newhost]
type = s3
provider = Other
access_key_id = xxx
secret_access_key = xxx
endpoint = http://localhost:28333
region = us-east-1
force_path_style = true