namespace: ""

traefik:
  namespace: ""

gitlab:
  namespace: ""

clusterDomain: ""

vault:
  namespace: ""

eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  kvEnginePath: ""
  secrets: []

configMaps:
  argocdCm:
    data: {}
  cmdParamsCm:
    data: {}
  gpgKeysCm:
    data: {}
  notificationsCm:
    data: {}
  rbacCm:
    data: {}
  sshKnownHostsCm:
    additional: []
  tlsCertsCm:
    data: {}
