apiVersion: v1
kind: Service
metadata:
  name: outline-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: outline-postgresql
    app.kubernetes.io/instance: outline-postgresql-{{ .Values.namespace }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: outline-postgresql
    app.kubernetes.io/instance: outline-postgresql-{{ .Values.namespace }}
