apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-backup-creds
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: xxx_base64
  AWS_SECRET_ACCESS_KEY: zzz_base64
  AWS_ENDPOINTS: www_base64
