# Namespace
namespace: ""

# Ingress settings
ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# Traefik namespace for middleware
traefik:
  namespace: ""

# Auto-unseal CronJob
autoUnseal:
  schedule: "*/5 * * * *"
  keyThreshold: 2
  credsHostPath: "/etc/kubernetes/vault-unseal.json"
  image: "alpine/k8s:1.35.0"
