namespace: ""
tolerations: []
nodeSelector: {}
resources:
  applicationController: {}
  applicationsetController: {}
  dexServer: {}
  notificationsController: {}
  redis: {}
  repoServer: {}
  server: {}
