namespace: ""
tolerations: []
nodeSelector: {}
resources:
  applicationController: {}
  applicationsetController: {}
  dexServer: {}
  notificationsController: {}
  redis: {}
  repoServer: {}
  server: {}
global:
  image:
    mainWithRegistry: ""
    mainTag: ""
    dexWithRegistry: ""
    dexTag: ""
    redisWithRegistry: ""
    redisTag: ""
