namespace: ""

ingressClass: ""
clusterIssuer: ""
entryPoints:
  web: "web"
  websecure: "websecure"
vpnOnlyEnabled: false
traefik:
  namespace: ""

prometheusIngress:
  domain: ""
  secretName: ""
  httpEnable: false
  httpsEnable: false

alertmanagerIngress:
  domain: ""
  secretName: ""
  httpEnable: false
  httpsEnable: false
