---
namespace: ""

alertmanagerSpec: {}
alertmanagerRootConfigSpec: {}

alertmanager:
  port: 0
  meshTcpPort: 0
  meshUdpPort: 0

# Custom K8s objects to render (operator-side, default empty)
extraObjects: []
