# =============================================================================
# INGRESS FOR ALERTMANAGER UI — HTTP (Traefik)
# =============================================================================

{{- if .Values.alertmanagerIngress.httpEnable }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-alertmanager-http
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    traefik.ingress.kubernetes.io/router.entrypoints: "{{ .Values.entryPoints.web }}"
    {{- if .Values.vpnOnlyEnabled }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-vpn-only@kubernetescrd"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClass }}
  rules:
    - host: {{ .Values.alertmanagerIngress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager-instance
                port:
                  number: 9093
{{- end }}
