# =============================================================================
# ARGOCD RBAC — ROLES (namespaced)
#   Ограничивают права одним namespace. Namespace и rules берутся из элемента.
# =============================================================================
{{- range $role := .Values.rbacRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $role.name }}
  namespace: {{ $role.namespace }}
  {{- with $role.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{ toYaml $role.rules | indent 2 }}
{{- end }}
