apiVersion: v1
kind: Service
metadata:
  name: zitadel-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: zitadel-postgresql
    app.kubernetes.io/instance: zitadel-postgresql-{{ .Values.namespace }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: zitadel
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: zitadel-postgresql
    app.kubernetes.io/instance: zitadel-postgresql-{{ .Values.namespace }}
