# Namespace
namespace: "zitadel"

# ZITADEL ingress settings
ingress:
  ingressClass: ""
  domain: ""
  clusterIssuer: ""
  tlsSecretName: ""
  vpnOnlyEnabled: false
  vpnIngressRouteMiddlewares: []
  httpEnabled: false

# Traefik namespace for middleware
traefik:
  namespace: ""
  entryPoints:
    web: ""
    websecure: ""
