# Namespace
namespace: "zitadel"

# ZITADEL ingress settings
ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  tlsSecretName: ""
  vpnOnlyEnabled: false
  httpEnabled: false

# Traefik namespace for middleware
traefik:
  namespace: ""
