{{- range .Values.appProjects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: "{{ $.Values.namespace }}"
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: "{{ $.Values.namespace }}"
  {{- if .finalizers }}
  finalizers:
    {{- toYaml .finalizers | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
