---
apiVersion: v2
name: linstor-post
description: LINSTOR / Piraeus post-install — Ingress + Certificate (controller GUI) + ServiceMonitor/PodMonitor (controller, satellite, affinity-controller)
type: application
version: 1.0.0
appVersion: "1.0.0"
