---
apiVersion: v2
name: linstor-post
description: LINSTOR / Piraeus post-install — ServiceMonitor + PodMonitor for linstor-controller, linstor-satellite, linstor-affinity-controller
type: application
version: 1.0.0
appVersion: "1.0.0"
