---
linstorController:
  serviceMonitor:
    enabled: false
    interval: ""
    scrapeTimeout: ""
    labels: {}

linstorSatellite:
  podMonitor:
    enabled: false
    interval: ""
    scrapeTimeout: ""
    labels: {}

linstorAffinityController:
  podMonitor:
    enabled: false
    interval: ""
    scrapeTimeout: ""
    labels: {}

# Custom K8s objects to render (operator-side, default empty)
extraObjects: []
