linstorController:
  serviceMonitor:
    enabled: false
    interval: ""
    scrapeTimeout: ""
    labels: {}

linstorSatellite:
  podMonitor:
    enabled: false
    interval: ""
    scrapeTimeout: ""
    labels: {}

linstorAffinityController:
  podMonitor:
    enabled: false
    interval: ""
    scrapeTimeout: ""
    labels: {}
