# =============================================================================
# Reload HAProxy service
# =============================================================================
# Uses graceful reload — no TCP connection interruption
# =============================================================================

---
- name: Reload haproxy service
  systemd:
    name: haproxy
    state: reloaded
