# =============================================================================
# Wait for kubelet to become active
# =============================================================================

---
- name: Wait for kubelet to be active
  command: systemctl is-active kubelet
  register: kubelet_status
  until: kubelet_status.stdout == 'active'
  retries: 12
  delay: 5
  changed_when: false

- name: Kubelet is ready
  debug:
    msg: "{{ new_hostname }}: kubelet running"
