# Vault namespace
namespace: ""

# DNS domain for internal service resolution
clusterDomain: ""

# Traefik namespace for ingress
traefik:
  namespace: ""

# External Secrets namespace
externalSecrets:
  namespace: ""

# ESO settings
eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  kvEnginePath: ""
  isNeedEso: true
  secrets: []

# ESO resources global config
esoResourcesConfig:
  secretStoreRefreshInterval: 60
  externalSecretRefreshInterval: "1m"
  externalSecretRefreshPolicy: "Periodic"
