# =============================================================================
# SECRET STORE FOR GITLAB SECRETS
# =============================================================================

{{- if not (eq .Values.gitlabEso.isNeedEso false) }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.gitlabEso.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.esoResourcesConfig.secretStoreRefreshInterval }}
  provider:
    vault:
      server: {{ .Values.gitlabEso.vaultServerUrl }}
      path: {{ .Values.gitlabEso.kvEnginePath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.gitlabEso.roleName }}
          serviceAccountRef:
            name: {{ .Values.gitlabEso.saName }}
{{- end }}
