# =============================================================================
# CUSTOM LONGHORN STORAGE CLASSES
# =============================================================================

{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: driver.longhorn.io
allowVolumeExpansion: {{ .allowVolumeExpansion }}
reclaimPolicy: {{ .reclaimPolicy | quote }}
volumeBindingMode: {{ .volumeBindingMode | quote }}
parameters:
{{ toYaml .parameters | indent 2 }}
{{- end }}
