# =============================================================================
# CERTIFICATES FOR SEAWEEDFS (cert-manager)
#   Каждый Certificate рендерится если <unit>CertificateConfig.enabled.
#   Полный raw spec из values.
# =============================================================================
{{- if .Values.s3CertificateConfig.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.s3CertificateConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
{{ toYaml .Values.s3CertificateConfig.spec | indent 2 }}
{{- end }}
{{- if .Values.masterCertificateConfig.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.masterCertificateConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
{{ toYaml .Values.masterCertificateConfig.spec | indent 2 }}
{{- end }}
{{- if .Values.filerCertificateConfig.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.filerCertificateConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
{{ toYaml .Values.filerCertificateConfig.spec | indent 2 }}
{{- end }}
{{- if .Values.adminCertificateConfig.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.adminCertificateConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
{{ toYaml .Values.adminCertificateConfig.spec | indent 2 }}
{{- end }}
