namespace: ""

ingress:
  ingressClass: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: true
  httpEnable: false
  httpsEnable: false

traefik:
  namespace: ""
  entryPoints:
    web: ""
    websecure: ""

storageClasses: []
