# =============================================================================
# ARGO EVENTS CLUSTER ROLES
#   Для случаев, когда источник или сенсор работает кластер-широко.
#   Правила берутся из values как есть.
# =============================================================================
{{- range $cr := .Values.rbacClusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $cr.name }}
rules:
{{ toYaml $cr.rules | indent 2 }}
{{- end }}
