namespace: ""

grafana:
  port: 3000

ingressClass: ""
clusterIssuer: ""
entryPoints:
  web: "web"
  websecure: "websecure"
vpnOnlyEnabled: false
traefik:
  namespace: ""

grafanaIngress:
  domain: ""
  secretName: ""
  httpEnable: false
  httpsEnable: false
