namespace: ""

ingressClass: ""
clusterIssuer: ""
vpnOnlyEnabled: false
traefik:
  namespace: ""
  entryPoints:
    web: "web"
    websecure: "websecure"

grafana:
  ingress:
    domain: ""
    secretName: ""
    httpEnable: false
    httpsEnable: false
  port: 3000
