namespace: ""

grafana:
  port: 3000

ingressClass: ""
clusterIssuer: ""
vpnOnlyEnabled: false
traefik:
  namespace: ""
  entryPoints:
    web: "web"
    websecure: "websecure"

grafanaIngress:
  domain: ""
  secretName: ""
  httpEnable: false
  httpsEnable: false
