# =============================================================================
# VPN TRAEFIK MIDDLEWARES
# =============================================================================

{{- range .Values.vpnMiddlewares }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
