namespace: ""

ingressClass: ""
clusterIssuer: ""

traefik:
  namespace: ""
  entryPoints:
    web: ""
    websecure: ""

prometheus:
  ingress:
    domain: ""
    secretName: ""
    vpnOnlyEnabled: false
    vpnIngressMiddlewares: ""
    httpEnable: false
    httpsEnable: false
  port: 9090

alertmanager:
  ingress:
    domain: ""
    secretName: ""
    vpnOnlyEnabled: false
    vpnIngressMiddlewares: ""
    httpEnable: false
    httpsEnable: false
  port: 9093