namespace: ""

grafana:
  port: 0
  image: ""
  installPlugins: ""
  externalUrl: ""

adminSecret:
  name: ""
  usernameKey: ""
  passwordKey: ""

pvc:
  storageClassName: ""
  storageSize: ""
  accessMode: ""
  subpath: ""

tolerations: []
nodeSelector: {}
resources: {}
