---
namespace: ""

grafana:
  port: 0
  image: ""
  installPlugins: ""
  externalUrl: ""

adminSecret:
  name: ""
  usernameKey: ""
  passwordKey: ""

database:
  type: ""
  host: ""
  name: ""
  user: ""
  sslMode: ""
  maxOpenConns: 0
  maxIdleConns: 0
  connMaxLifetime: ""

databasePasswordSecretName: ""

tolerations: []
nodeSelector: {}
resources: {}

# Custom K8s objects to render (operator-side, default empty)
extraObjects: []
