---
namespace: ""

grafana:
  port: 0
  image: ""
  installPlugins: ""
  externalUrl: ""
  oidc:
    enabled: false
    name: ""
    k8sSecretName: ""
    clientIdKey: ""
    clientSecretKey: ""
    authUrl: ""
    tokenUrl: ""
    apiUrl: ""
    scopes: ""
    allowSignUp: ""
    usePkce: ""
    loginAttributePath: ""
    emailAttributePath: ""
    nameAttributePath: ""
    skipOrgRoleSync: ""

adminSecret:
  name: ""
  usernameKey: ""
  passwordKey: ""

database:
  type: ""
  host: ""
  name: ""
  sslMode: ""
  maxOpenConns: 0
  maxIdleConns: 0
  connMaxLifetime: ""
  credentialsSecretName: ""
  usernameKey: ""
  passwordKey: ""

tolerations: []
nodeSelector: {}
resources: {}

# Custom K8s objects to render (operator-side, default empty)
extraObjects: []
