namespace: "teleport"

roles: []
users: []
bots: []
provisionTokens: []
apps: []
databases: []
githubConnectors: []
oidcConnectors: []
samlConnectors: []
accessLists: []
trustedClusters: []
loginRules: []
accessMonitoringRules: []
oktaImportRules: []
opensshServers: []
opensshEiceServers: []
workloadIdentities: []
inferenceModels: []
inferencePolicies: []
inferenceSecrets: []
autoupdateConfigs: []
autoupdateVersions: []
