{{- range .Values.apps }}
---
apiVersion: resources.teleport.dev/v3
kind: TeleportAppV3
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
