{{- range .Values.autoupdateConfigs }}
---
apiVersion: resources.teleport.dev/v1
kind: TeleportAutoUpdateConfigV1
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}

{{- range .Values.autoupdateVersions }}
---
apiVersion: resources.teleport.dev/v1
kind: TeleportAutoUpdateVersionV1
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
