{{- range .Values.inferenceModels }}
---
apiVersion: resources.teleport.dev/v1
kind: TeleportInferenceModel
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}

{{- range .Values.inferencePolicies }}
---
apiVersion: resources.teleport.dev/v1
kind: TeleportInferencePolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}

{{- range .Values.inferenceSecrets }}
---
apiVersion: resources.teleport.dev/v1
kind: TeleportInferenceSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
